[BE] 로그인 기능 구현 (#171, #186)
woowacourse-teams/2024-corea pull request #197
Opened 2024-08-05 07:49 UTC by hjk0761

## 📌 관련 이슈

- closed: #171 
- closed: #186 

## ✨ PR 세부 내용

로그인 기능을 구현했습니다.
정말... 힘들었습니다.

전체적인 흐름은 다음과 같습니다.

로그인 과정에서 생성되는 토큰이 두 개가 있습니다.
access token 은 만료기간이 30분으로 짧은 대신, 이 친구로 로그인 상태를 유지합니다.
결국 로그인이 필요한 모든 api 에서 해당 토큰을 헤더에 담아서 사용하게 됩니다.
jwt 의 특성 상 토큰을 해석하는 과정에서 만료되었다면 예외가 발생하는데,
이 때를 위해 비로소 refresh token 을 사용하게 됩니다.

refresh token 은 만료기간이 7일로 길고, 서버와 웹 모두 저장하는 토큰입니다.
토큰 만료로 인해 예외가 발생했다면 먼저 웹으로 401 예외를 보내고, 이후에 refresh token 을 담아 access token 재발급 요청을 받게 됩니다.
이 때 refresh token 을 검증하여 올바르다면 새로운 access token 을 만들어서 웹으로 보내고, 아니라면 로그아웃되게 구현했습니다.

---
고민 포인트

LoginService - validateRefreshToken 메서드에 대해서 고민이 많았는데, 이를 해결할 더 좋은 방법을 찾기 못해 일단 이런 구조로 구현하게 되었습니다.

아래는 구현하면서 생긴 논의점입니다.
EnableConfigurationProperties 사용 위치 - Service, infrastructure 에서 사용하는게 괜찮을지에 대해 논의하고 싶은데, 설정 파일에 있는 값을 현재와 같이 service, infrastructure 단위에서 사용하는거에 대해 괜찮은지 의견 주시면 감사하겠습니다 ㅎㅎ

2024-08-05 15:47 UTC, youngsu5582 requested changes
무빈 되게되게 수고한거 많이 알지만
계층간 침범이나 역활이 두개 이상 하는 부분들이 느껴져서 RC 로 남기겠습니다.
혹시 힘들거나 시간이 부족하면 말해주면 같이 해결해나가도 좋을거 같아용 🙂🙂

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/infrastructure/TokenProvider.java
> +        Map<String, ?> claims = createClaimsByMember(member);
밑에서는 Object 로 선언했는데
위에서는 `?` 로 선언한 이유가 있나요?

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/interceptor/AuthorizationInterceptor.java
> +    private boolean checkAnnotation(Object handler, Class<LoginMember> loginMemberClass) {
해당 부분에서 굳이 LoginMember.class 를 주입할 필요는 안느껴지는데


```java
private boolean checkAnnotation(Object handler) {
    if (handler instanceof ResourceHttpRequestHandler) {
        return false;
    }

    HandlerMethod handlerMethod = (HandlerMethod) handler;

    return (null != handlerMethod.getMethodAnnotation(LoginMember.class) ||
            null != handlerMethod.getBeanType().getAnnotation(LoginMember.class));
}
```
이렇게 넣거나
```java
private static final Class<LoginMember> AUTH_ANNOTATION = LoginMember.class;

    private boolean checkAnnotation(Object handler) {
        if (handler instanceof ResourceHttpRequestHandler) {
            return false;
        }

        HandlerMethod handlerMethod = (HandlerMethod) handler;

        return (null != handlerMethod.getMethodAnnotation(AUTH_ANNOTATION) ||
                null != handlerMethod.getBeanType().getAnnotation(AUTH_ANNOTATION));
    }
```
이런 방식도 가능할듯?

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/domain/LoginInfo.java
> +public class LoginInfo {
단순한 생각으론 Member 에 RefreshToken 을 추가해도 괜찮지 않을까 생각했는데
분리한 이유가 있을까요??

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/infrastructure/GithubClient.java
> +public class GithubClient {
해당 부분에 변수들 상수 처리해도 괜찮을듯용

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +    public ResponseEntity<Void> login(HttpServletRequest request) {
여기서 `@RequestParam` 을 사용하지 않은 이유가 있나요?

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +        String accessToken = githubClient.getAccessToken(code);
Controller 가 굳이 accessToken 을 받고 
그걸 기반으로 userInfo 를 받는다는걸 알 필요가 없을꺼 같아요.

그냥 code 넣고 `GithubUserInfo` 을 받아도 된다구 생각함당.

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +        Member member = memberService.login(userInfo);
도메인이 레이어 계층까지 역류 되는거 같은데
위와 같이 숨기는 것도 나쁘진 않을거 같아용 🙂

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +    public ResponseEntity<Void> extendAuthorization(HttpServletRequest request) {
이것도 위처럼 컨트롤러가 너무 많은걸 아는거 같아용

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/service/LoginService.java
> +    public Cookie createRefreshCookie(Member member) {
Cookie 는 웹 계층에서 사용되는 값
( `import jakarta.servlet.http.Cookie;` import 문 역시도 http )
이며 createRefreshCookie 문은 온전히 cookie 를 만들어 준다고 유추할 꺼 같은데 `save` 문도 있어서 두 가지 일을 한 Service 에서 하는거 같습니다.

두개를 분리하는 거도 좋을꺼 같아용

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/domain/GithubUserInfo.java
> +        String avatar_url,
`@JsonProperty` 를 사용해서
컨벤션인 카멜케이스를 준수하는건 어떨까요?

2024-08-05 15:47 UTC, youngsu5582 commented on backend/src/main/java/corea/auth/RequestHandler.java
>      private static final String AUTHORIZATION_HEADER = "Authorization";
AUTHORIZATION_HEADER 나 ANONUMOUS 같이 다른 곳에서도 공용적으로 사용되는건
global constant 에서 관리해도 괜찮을 거 같습니다.

2024-08-06 05:20 UTC, jcoding-play approved these changes
코드 깔끔하고 좋은것같아요~~
수고 많으셨습니당~~

2024-08-06 06:13 UTC, ashsty commented on backend/src/main/java/corea/auth/RequestHandler.java
> +        if (request.getHeader(AUTHORIZATION_HEADER) != null && request.getHeader(AUTHORIZATION_HEADER).startsWith("Bearer ")) {
"bearer"도 constant로 뺄까여?

2024-08-06 06:13 UTC, ashsty commented on backend/src/main/java/corea/auth/controller/LoginControllerSpecification.java
> +
```suggestion
```

2024-08-06 06:13 UTC, ashsty commented on backend/src/main/java/corea/auth/domain/LoginInfo.java
> +public class LoginInfo {
위와 같이 설계하면 로그인할 때마다 멤버 정보가 업데이트되는 거 아닌가요? 🤔
아닐수도...

2024-08-06 06:13 UTC, ashsty commented on backend/src/test/java/corea/room/acceptance/RoomAcceptanceTest.java
> +@Transactional
이거 왜 붙어있는거였죠? 이유가 있나요?

2024-08-06 06:36 UTC, hjk0761 commented on backend/src/main/java/corea/member/service/MemberService.java
> +public class MemberService {
auth 패키지의 loginService 로 옮겼습니다!

2024-08-06 06:41 UTC, hjk0761 commented on backend/src/main/java/corea/member/service/MemberService.java
> +                .orElse(register(new Member(userInfo.login(), userInfo.avatar_url(), userInfo.name(), userInfo.email(), true, 0.0f)));
👍

2024-08-06 06:44 UTC, ashsty commented on backend/src/main/java/corea/auth/infrastructure/TokenProvider.java
> +        Map<String, ?> claims = createClaimsByMember(member);
없어염~~ ㅎㅎ

2024-08-06 06:50 UTC, ashsty commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +    public ResponseEntity<Void> login(HttpServletRequest request) {
없어염 ㅎㅎ 감사링!

2024-08-06 07:04 UTC, hjk0761 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +    public ResponseEntity<Void> login(HttpServletRequest request) {
명세에 맞게 `@RequestBody`로 바꿨습니다 ㅎㅎ 
HttpSevletRequest 를 쓴건 이유가 있는건 아니였습니다!

2024-08-06 07:18 UTC, hjk0761 commented on backend/src/main/java/corea/auth/controller/LoginController.java
> +        String accessToken = githubClient.getAccessToken(code);
서비스 계층만 볼 수 있도록 수정했습니다~

2024-08-06 07:47 UTC, hjk0761 commented on backend/src/main/java/corea/auth/service/LoginService.java
> +    public Cookie createRefreshCookie(Member member) {
CookieProvider 를 분리해서, 웹 계층에서 사용하는 건 컨트롤러에서 연결할 수 있도록 분리했습니다!

2024-08-06 08:43 UTC, youngsu5582 approved these changes
굳굳

2024-08-06 08:46 UTC, ashsty approved these changes

2024-08-06 08:46 UTC, ashsty commented on backend/src/main/java/corea/auth/infrastructure/TokenProvider.java
> +    public Long findMemberIdByToken(String token) {
메소드 순서 getPayLoad 위로 올려주세용 ㅇ.ㅇ

2024-08-06 09:03 UTC, merged