[FE] 메인 페이지 배너 만들기(#298)
woowacourse-teams/2024-corea pull request #305
Opened 2024-08-16 06:43 UTC by chlwlstlf

## 📌 관련 이슈

- closed: #298 

## ✨ PR 세부 내용

- 배너 만들었습니다.
- 디자인 이상하면 바로 말씀해주세요!!! (제가 봐도 좀 이상함)

2024-08-16 06:55 UTC, pp449 approved these changes
이 시대 최고의 배너 👍👍

2024-08-16 06:55 UTC, pp449 commented on frontend/src/components/main/banner/Banner.tsx
> +        <CyclingClasses items={["코드", "개발자", "리뷰", "리뷰어", "리뷰이"]} speed={4100} />
요거 선언을 따로 분리하는것도 좋을거 같아요

2024-08-16 16:39 UTC, chlwlstlf commented on frontend/src/components/main/banner/Banner.tsx
> +        <CyclingClasses items={["코드", "개발자", "리뷰", "리뷰어", "리뷰이"]} speed={4100} />
넵! firstItems, secondItems로 분리했습니다~~

2024-08-18 12:00 UTC, 00kang requested changes
저희 이런 느낌으로 배너 구성하는 건 어떨까요?
README.md에 적었던 서비스 소개 글이랑 텐텐이 작업한 ~~와~~을 잇다 를 적절하게 배치하면 되지 않을까 싶은데 어떻게 생각하시나용
![image](https://github.com/user-attachments/assets/9a84c034-1726-4eb3-995d-5d6f96f9812f)

2024-08-19 04:55 UTC, 00kang approved these changes
머지합니다~

2024-08-19 04:55 UTC, merged

2024-08-19 05:02 UTC, chlwlstlf commented on frontend/src/components/main/banner/Banner.tsx
> +        <span>를 연결합니다</span>
한나체가 굵어서 이쁠 것 같네요! 좋습니다ㅎㅎㅎ