[FE] test: MSW 핸들러 설정 추가(#57)
woowacourse-teams/2024-corea pull request #59
Opened 2024-07-18 07:59 UTC by pp449

## 📌 관련 이슈

- closed: #57

## ✨ PR 세부 내용
API 명세서에 기재된 내용으로 MSW Handler 추가

2024-07-19 01:26 UTC, 00kang requested changes
api 명세서를 기반으로 다시 확인해주시면 좋을 것 같아요 👍

2024-07-19 01:26 UTC, 00kang commented on frontend/src/apis/endpoints.ts
> +  },
특정 방 참여를 신청하는 api의 endpoint가 추가되면 좋을 것 같아요 !
```
url : localhost:8080/participate/{id}
method: POST
```

2024-07-19 01:26 UTC, 00kang commented on frontend/src/mocks/handler/roomHandler.ts
> +const roomHandler = [
특정 방 참여를 신청하는 api의 endpoint를 추가하면 여기도 수정되어야 할 것 같아요 ~

2024-07-19 01:32 UTC, chlwlstlf approved these changes

2024-07-19 01:32 UTC, chlwlstlf commented on frontend/src/mocks/server.ts
> +export const server = setupServer(...roomHandler);
```ts
import { handlers as cartItemHandlers } from './cartItem/cartItem';
import { handlers as productHandlers } from './product/product';

const handlers = [...productHandlers, ...cartItemHandlers];

export default handlers;
```

위의 코드 예시처럼
room과 review를 분리한 후 handler.ts를 만들어서 여기서 합치는 건 어떻게 생각하시나요???
너무 많은 파일 분리라고 생각하시면 넘어가주셔도 됩니다 ~😉

2024-07-19 01:32 UTC, chlwlstlf commented on frontend/src/mocks/handler/roomHandler.ts
> +  }),
수고하셨습니다! 코드가 깔끔하여 보기 편하네요ㅎㅎ
추후에 review 관련된 건 분리하셔도 좋을 것 같아요! 지금 pr에서는 아직 api가 적어서 괜찮은 것 같습니다.

2024-07-20 11:51 UTC, pp449 commented on frontend/src/apis/endpoints.ts
> +  },
꼼꼼하게 다 봐줬군요 😄
제가 엔드포인트를 잘못 설정해뒀었는데 해당 내용 수정했어요!

2024-07-20 11:52 UTC, pp449 commented on frontend/src/mocks/server.ts
> +export const server = setupServer(...roomHandler);
코드가 다를게 없다 생각하는데 요건 나중에 고려해 보도록해요~

2024-07-20 14:46 UTC, 00kang approved these changes

2024-07-20 14:48 UTC, 00kang commented
수정 확인해서 머지하겠습니당~

2024-07-20 14:48 UTC, merged