[BE] 리뷰어, 리뷰이 조회 API 기능 구현 (#26, #34)
woowacourse-teams/2024-corea pull request #91
Opened 2024-07-22 08:47 UTC by hjk0761

## 📌 관련 이슈

- closed: #26 
- closed: #34

## ✨ PR 세부 내용

리뷰어, 리뷰이 조회 API 기능 구현했습니다.
이에 따라서 불필요한 파일은 없앴습니다.

swagger 설정 파일 임의로 수정해 두었습니다.

컨트롤러 메서드 순서는 임시로 두었습니다.
RoomController 가 많은 수정이 있을 것으로 예상되어 그렇게 했습니다.

DTO 에서 정적 팩토리 메서드 네이밍에 대해, 시그니쳐 수에 따라 하나면 from, 복수면 of 를 사용하는 것으로 알고 있지만 앞서 from 으로 사용해서 일단 맞췄습니다. 이에 대해선 논의해 보시죠~

2024-07-22 18:47 UTC, jcoding-play approved these changes

2024-07-22 18:47 UTC, jcoding-play commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    }
중복 코드 이렇게 바꿔봐도 좋을듯?? (그냥 대충 생각나는대로 여기다 바로 적어서 실행 될지 안될지는 잘 모르겠네용~ㅎㅎ)

당연히 보고 좀 과하다 싶으면 안 바꿔도 됩니다~

```java
public class MatchResultService {
    ...

    public List<ReviewInfo> findReviewers(long memberId, long roomId) {
        validateValidIds(memberId, roomId);
        List<MatchResult> results = matchResultRepository.findAllByToMemberIdAndRoomId(memberId, roomId);

        return 메서드명(results, result -> result.getFromMember());
    }

    public List<ReviewInfo> findReviewees(long memberId, long roomId) {
        validateValidIds(memberId, roomId);
        List<MatchResult> results = matchResultRepository.findAllByFromMemberIdAndRoomId(memberId, roomId);

        return 메서드명(results, result -> result.getToMember());
    }

    private List<ReviewInfo> 메서드명(List<MatchResult> results, Function<MatchResult, long> function) {
        return results.stream()
                .map(result -> function.apply(result))
                .toList();
    }
```

2024-07-22 18:47 UTC, jcoding-play commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +@Import(DataInitializer.class)
필요한가요?

2024-07-22 18:47 UTC, jcoding-play commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +@Transactional
테스트에서 `@Transactional` 어노테이션 사용하여 발생할 수 있는 문제점을 알고 있나요??
모른다면 한번 검색해서 찾아봐도 좋을 것 같습니다~

`@Transactional` 어노테이션을 지우라는 뜻은 아니고 발생할 수 있는 문제점을 알고 쓴다면 더 좋을 것 같아 커멘트 남겨요~

2024-07-22 18:47 UTC, jcoding-play commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +    }
테스트 코드에서 불필요하게 지역변수로 추출하는 것 같다 느껴져요~

```suggestion
    @Test
    @DisplayName("리뷰어 결과를 가져올 때 존재하지 않는 방이나 사용자의 정보를 요청하는 경우 예외를 발생한다.")
    void findReviewersInvalidException2() {      
        List<Participation> participations = new ArrayList<>();
        participations.add(new Participation(1L, 1L));
        participations.add(new Participation(1L, 4L));
        participations.add(new Participation(1L, 5L));
        participations.add(new Participation(1L, 6L));
        participations.add(new Participation(1L, 7L));

        matchingService.matchMaking(participations, 3);

        assertThatThrownBy(() -> matchResultService.findReviewers(8, 1))
                .isInstanceOf(CoreaException.class)
                .hasMessage("8에 해당하는 멤버가 없습니다.");
    }
```

2024-07-23 01:24 UTC, youngsu5582 commented on backend/src/main/java/corea/matching/dto/ReviewInfo.java
> +        return new ReviewInfo(member.getId(), member.getName(), matchResult.getPrLink(), matchResult.getReviewStatus());
getUsername 이 맞는거 같은데
( name 을 받을수 있는지 불여부 )
해당 부분은 주석 처리나, 더욱 명확하게 명시하는게 좋을 꺼 같아용

2024-07-23 01:25 UTC, hjk0761 commented on backend/src/main/java/corea/matching/dto/ReviewInfo.java
> +    }
그럼 기본 네이밍에 맞게 of 로 수정하겠습니다!

2024-07-23 01:26 UTC, hjk0761 commented on backend/src/main/java/corea/matching/dto/ReviewInfo.java
> +        return new ReviewInfo(member.getId(), member.getName(), matchResult.getPrLink(), matchResult.getReviewStatus());
오 놓친 부분이었는데 감사해요 ㅎ.ㅎ

2024-07-23 01:45 UTC, hjk0761 commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +@Import(DataInitializer.class)
멤버와 방이 이미 DataInitializer 에 잘 정의가 되어있어 사용했습니다!

2024-07-23 02:06 UTC, youngsu5582 requested changes
보다가 궁금한 부분들이 생겨서 Request Changes 로 할게용🙂
코드 짠다구 수고했슴당

2024-07-23 02:06 UTC, youngsu5582 commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +    void findReviewersInvalidException() {
사실
저는 테스트에서 메시지 까지 검증하는걸 별로 안 좋아합니당.

물론 Enum 안에 있기도 하고 `해당하는 방` 과 `해당하는 멤버` 는 엄연히 다르지만 
그게 진정으로 중요한가 라는 생각이 들어서입니다. ( 일종의 view 영역 )

메시지를 검증할거면, 차라리 안에 있는 Exception EnumType 을 검증하는건 어떨까요??
( 메시지가 변해도, 발생한 예외는 비즈니스 로직과 명확하게 같이 이동 )

2024-07-23 02:06 UTC, youngsu5582 commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    private void validateValidIds(long memberId, long roomId) {
이미 `validate` 가 있는데 뒤에 `Valid` 를 명시할 필요는 없다고 생각해요.
당장은 존재하는지만 검증하는게 같은데
`validateExist` 까지만 해도

"memberId 와 roomId가 존재하는지 검증하는구나" 
로 생각할 꺼 같은데 어떤지

2024-07-23 02:11 UTC, hjk0761 commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    public List<ReviewInfo> findReviewers(long memberId, long roomId) {
컨벤션을 따르도록 포장해 반환했습니다 ㅎㅎ 짚어주셔서 감사해요~

2024-07-23 02:14 UTC, hjk0761 commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    }
좋은 아이디어인 것 같습니다!
다만, 더 이상의 재사용 필요성이 느껴지지 않아 추출하진 않았습니다.

아이디어 잘 가지고 있을께용!

2024-07-23 03:50 UTC, jcoding-play commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +@Import(DataInitializer.class)
`@Import(DataInitializer.class)`를 빼도 잘 동작할거 같다는 뜻이었어요~

2024-07-23 03:52 UTC, jcoding-play commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    private void validateValidIds(long memberId, long roomId) {
동의합니다~ 메서드명 말할까 말까 고민 많이 함ㅎ

2024-07-23 04:04 UTC, hjk0761 commented on backend/src/main/java/corea/matching/dto/ReviewInfo.java
> +public record ReviewInfo(Long userId, String username, String link, ReviewStatus isReviewed) {
원시 타입으로 변경했습니다 ㅎㅎ

2024-07-23 04:33 UTC, hjk0761 commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +@Import(DataInitializer.class)
수정했어용 ㅎ.ㅎ

2024-07-23 04:34 UTC, hjk0761 commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +    }
나중에 DataInitializer 가 더 명확해지면, 그 때 가시적으로 데이터를 사용할 수 있을 것 같아 지금은 수정하지 않겠습니다!

2024-07-23 04:44 UTC, hjk0761 commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +    void findReviewersInvalidException() {
hasFieldOrPropertyWithValue("exceptionType", ---) 를 사용해서 EnumType 을 검증하도록 수정했습니다~

2024-07-23 04:46 UTC, hjk0761 commented on backend/src/main/java/corea/matching/service/MatchResultService.java
> +    private void validateValidIds(long memberId, long roomId) {
`validateExistence` 로 수정했습니다~

2024-07-23 04:47 UTC, ashsty commented on backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
> +        List<Participation> participations = new ArrayList<>();
[논의 결과]

추가 로직이 없는 상황에서 해당 일급 컬렉션을 구현하는 건 불필요한 코스트라고 생각되어 우선 보류하였습니다.
추후 필요성이 느껴진다면 재논의하도록 하겠습니다.

2024-07-23 04:56 UTC, ashsty approved these changes

2024-07-23 05:12 UTC, youngsu5582 approved these changes
굳이용 👍

2024-07-23 05:13 UTC, merged